services:
  - type: web
    name: 7-star-salon
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_SETUP_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        value: saloon-b111a.appspot.com
      - key: SALON_NAME
        value: 7 Star Salon
      - key: CURRENCY_SYMBOL
        value: Rs
      - key: WHATSAPP_NUMBER
        value: "919980480428"
      - key: MAPS_QUERY
        value: "7 Star Salon, Lingegowdanadoddi"
      - key: FLASK_DEBUG
        value: "false"
